### ISSUE TITLE
Implement PowerSearch Part 2

### ISSUE THREAD

**Issue by nuruddinmazlan** [cs2103jan2015-t15-3j/main#46]
1) Implement PowerSearch based on weightage of 60% with taskName and remarks.
2)For example: the input is Adamant
Results are : Badman, Adman, Advant, Damn, etc. 
3) See how that the first alphabet doesn't match the input but based on the number of matched characters that equals to 60% or more, it returns these strings.
4) This is like an auto-suggestion in Google

**Comment by sammyzx** [comment]
done!
